version: "3"

services:
  #############################
  # ELASTICSEARCH MASTER NODE #
  #############################
  master:
    restart: unless-stopped
    image: blacktop/elasticsearch:x-pack
    environment:
      - cluster.name=docker-cluster
      - network.host=0
      - ELASTIC_PASSWORD=pleasechangeme
      - xpack.security.audit.enabled=true
      - node.master=true
      - node.ingest=false
      - node.data=false
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - elastic
  ####################################
  # ELASTICSEARCH CLIENT/INGEST NODE #
  ####################################
  ingest:
    restart: unless-stopped
    image: blacktop/elasticsearch:x-pack
    environment:
      - cluster.name=docker-cluster
      - network.host=0
      - ELASTIC_PASSWORD=pleasechangeme
      - xpack.security.audit.enabled=true
      - node.master=true
      - node.ingest=true
      - node.data=false
      - discovery.zen.ping.unicast.hosts=master
    ports:
      - "9200:9200"
    links:
     - master:elastic-master
    networks:
      - elastic
  ###########################
  # ELASTICSEARCH DATA NODE #
  ###########################
  data:
    restart: unless-stopped
    image: blacktop/elasticsearch:x-pack
    environment:
      - cluster.name=docker-cluster
      - network.host=0
      - ELASTIC_PASSWORD=pleasechangeme
      - xpack.security.audit.enabled=true
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - node.master=false
      - node.ingest=false
      - node.data=true
      - discovery.zen.ping.unicast.hosts=master
    links:
     - master:elastic-master
    # volumes:
    #   - data:/usr/share/elasticsearch/data
    networks:
      - elastic
  ###############
  # KIBANA NODE #
  ###############
  kibana:
    image: blacktop/kibana:x-pack
    ports:
      - "80:5601"
    links:
     - ingest:elasticsearch
    environment:
      - elasticsearch.url=http://elasticsearch:9200
      - elasticsearch.username=elastic
      - elasticsearch.password=pleasechangeme
      - xpack.monitoring.ui.container.elasticsearch.enabled=true
    networks:
      - elastic
#############################
# ELASTICSEARCH DATA VOLUME #
#############################
volumes:
  data:
################################
# ELASTICSEARCH BRIDGE NETWORK #
################################
networks:
  elastic:
    driver: bridge
